/******************************************************
        Name        : mykvh_ChangePasswordSuccessClass_Test
        Description : test class for mykvh_ChangePasswordSuccessClass 
*******************************************************/
@isTest
private class mykvh_ChangePasswordSuccessClass_Test{
     static testMethod void testmykvh_ChangePasswordSuccessClass(){
         mykvh_ChangePasswordSuccessClass ctrl = new mykvh_ChangePasswordSuccessClass();
         
     }
}